# This file was generated by GoReleaser. DO NOT EDIT.
class PachctlAT1.12 < Formula
  desc "Reproducible data science"
  homepage "https://www.pachyderm.com/"
  version "1.12.0-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pachyderm/pachyderm/releases/download/v1.12.0-rc1/pachctl_1.12.0-rc1_darwin_amd64.zip"
    sha256 "62d879e7c4456ad05b073b45ce6ba546048cdb7ebf0738b7f53abd0185573da0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pachyderm/pachyderm/releases/download/v1.12.0-rc1/pachctl_1.12.0-rc1_linux_amd64.tar.gz"
      sha256 "285c9111b127d8075a982c8be364806af502f2217b332944cb35d07e668590eb"
    end
  end

  def install
    bin.install buildpath/"pachctl"
  end

  test do
    system "#{bin}/pachctl version"
  end
end
